steps:
  - name: 'gcr.io/cloud-builders/docker'
    # gen-lang-client-0406445494
    # build -t europe-west9-docker.pkg.dev/gen-lang-client-0406445494/kubeflow/kubeflow .
    # gcloud builds submit \
    #    --region=europe-west9 --config \
    #    cloudbuild.yaml

    # Configure docker to have nessesary permissions: gcloud auth configure-docker europe-west9-docker.pkg.dev

    # ssh into the VM: gcloud compute ssh instance-20240810-091553 --zone us-central1-f
    args: ["build", "-t", "us-central1-docker.pkg.dev/gen-lang-client-0406445494/kubeflow/kubeflow", "."]
  - name: 'gcr.io/cloud-builders/docker'
    # gen-lang-client-0406445494
    args: ["push", "us-central1-docker.pkg.dev/gen-lang-client-0406445494/kubeflow/kubeflow"]